apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: freescout-app
  name: {{ .Values.app.metadata.name }}
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.app.spec.replicas }}
  selector:
    matchLabels:
      io.kompose.service: freescout-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/nginx-proxy: "true"
        io.kompose.service: freescout-app
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              value: {{ .Values.app.spec.template.spec.containers.env.ADMIN_EMAIL }}
            - name: ADMIN_PASS
              value: {{ .Values.app.spec.template.spec.containers.env.ADMIN_PASS }}
            - name: CONTAINER_NAME
              value: {{ .Values.app.spec.template.spec.containers.env.CONTAINER_NAME }}
            - name: DB_HOST
              value: {{ .Values.app.spec.template.spec.containers.env.DB_HOST }}
            - name: DB_NAME
              value: {{ .Values.app.spec.template.spec.containers.env.DB_NAME }}
            - name: DB_PASS
              value: {{ .Values.app.spec.template.spec.containers.env.DB_PASS }}
            - name: DB_USER
              value: {{ .Values.app.spec.template.spec.containers.env.DB_USER }}
            - name: DISPLAY_ERRORS
              value: "FALSE"
            - name: ENABLE_SSL_PROXY
              value: "TRUE"
            - name: LETSENCRYPT_EMAIL
              value: {{ .Values.app.spec.template.spec.containers.env.LETSENCRYPT_EMAIL }}
            - name: LETSENCRYPT_HOST
              value: {{ .Values.app.spec.template.spec.containers.env.LETSENCRYPT_HOST }}
            - name: SITE_URL
              value: {{ .Values.app.spec.template.spec.containers.env.SITE_URL }}
            - name: TIMEZONE
              value: Singapore
            - name: VIRTUAL_HOST
              value: {{ .Values.app.spec.template.spec.containers.env.VIRTUAL_HOST }}
            - name: VIRTUAL_NETWORK
              value: nginx-proxy
            - name: VIRTUAL_PORT
              value: "80"
          image: tiredofit/freescout
          name: freescout-app
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: freescout-app-claim0
            - mountPath: /www/logs
              name: freescout-app-claim1
      restartPolicy: Always
      volumes:
        - name: freescout-app-claim0
          persistentVolumeClaim:
            claimName: freescout-app-claim0
        - name: freescout-app-claim1
          persistentVolumeClaim:
            claimName: freescout-app-claim1
status: {}
