apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: freescout-app
  name: freescout-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: freescout-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/nginx-proxy: "true"
        io.kompose.service: freescout-app
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              value: admin@admin.com
            - name: ADMIN_PASS
              value: freescout
            - name: CONTAINER_NAME
              value: freescout-app
            - name: DB_HOST
              value: freescout-db
            - name: DB_NAME
              value: freescout
            - name: DB_PASS
              value: freescout
            - name: DB_USER
              value: freescout
            - name: DISPLAY_ERRORS
              value: "FALSE"
            - name: ENABLE_SSL_PROXY
              value: "TRUE"
            - name: LETSENCRYPT_EMAIL
              value: admin@example.com
            - name: LETSENCRYPT_HOST
              value: freescout.example.com
            - name: SITE_URL
              value: https://freescout.example.com
            - name: TIMEZONE
              value: America/Vancouver
            - name: VIRTUAL_HOST
              value: freescout.example.com
            - name: VIRTUAL_NETWORK
              value: nginx-proxy
            - name: VIRTUAL_PORT
              value: "80"
          image: tiredofit/freescout
          name: freescout-app
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: freescout-app-claim0
            - mountPath: /www/logs
              name: freescout-app-claim1
      restartPolicy: Always
      volumes:
        - name: freescout-app-claim0
          persistentVolumeClaim:
            claimName: freescout-app-claim0
        - name: freescout-app-claim1
          persistentVolumeClaim:
            claimName: freescout-app-claim1
status: {}
