apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: freescout-db-backup-claim0
  name: freescout-db-backup-claim0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.freescout-db-backup-claim0.storage }}
status: {}
