apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o test.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-app
      name: freescout-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: freescout-app
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml -o test.yml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/nginx-proxy: "true"
            io.kompose.service: freescout-app
        spec:
          containers:
            - env:
                - name: ADMIN_EMAIL
                  value: admin@admin.com
                - name: ADMIN_PASS
                  value: freescout
                - name: CONTAINER_NAME
                  value: freescout-app
                - name: DB_HOST
                  value: freescout-db
                - name: DB_NAME
                  value: freescout
                - name: DB_PASS
                  value: freescout
                - name: DB_USER
                  value: freescout
                - name: DISPLAY_ERRORS
                  value: "FALSE"
                - name: ENABLE_SSL_PROXY
                  value: "TRUE"
                - name: LETSENCRYPT_EMAIL
                  value: admin@example.com
                - name: LETSENCRYPT_HOST
                  value: freescout.example.com
                - name: SITE_URL
                  value: https://freescout.example.com
                - name: TIMEZONE
                  value: America/Vancouver
                - name: VIRTUAL_HOST
                  value: freescout.example.com
                - name: VIRTUAL_NETWORK
                  value: nginx-proxy
                - name: VIRTUAL_PORT
                  value: "80"
              image: tiredofit/freescout
              name: freescout-app
              resources: {}
              volumeMounts:
                - mountPath: /data
                  name: freescout-app-claim0
                - mountPath: /www/logs
                  name: freescout-app-claim1
          restartPolicy: Always
          volumes:
            - name: freescout-app-claim0
              persistentVolumeClaim:
                claimName: freescout-app-claim0
            - name: freescout-app-claim1
              persistentVolumeClaim:
                claimName: freescout-app-claim1
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-app-claim0
      name: freescout-app-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-app-claim1
      name: freescout-app-claim1
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: nginx-proxy
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/nginx-proxy: "true"
      podSelector:
        matchLabels:
          io.kompose.network/nginx-proxy: "true"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o test.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-db
      name: freescout-db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: freescout-db
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml -o test.yml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/nginx-proxy: "true"
            io.kompose.service: freescout-db
        spec:
          containers:
            - env:
                - name: CONTAINER_NAME
                  value: freescout-db
                - name: DB_NAME
                  value: freescout
                - name: DB_PASS
                  value: freescout
                - name: DB_USER
                  value: freescout
                - name: ROOT_PASS
                  value: password
              image: tiredofit/mariadb
              name: freescout-db
              resources: {}
              volumeMounts:
                - mountPath: /var/lib/mysql
                  name: freescout-db-claim0
          restartPolicy: Always
          volumes:
            - name: freescout-db-claim0
              persistentVolumeClaim:
                claimName: freescout-db-claim0
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-db-claim0
      name: freescout-db-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o test.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-db-backup
      name: freescout-db-backup
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: freescout-db-backup
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml -o test.yml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/nginx-proxy: "true"
            io.kompose.service: freescout-db-backup
        spec:
          containers:
            - env:
                - name: COMPRESSION
                  value: BZ
                - name: CONTAINER_NAME
                  value: freescout-db-backup
                - name: DB_CLEANUP_TIME
                  value: "8640"
                - name: DB_DUMP_BEGIN
                  value: "0000"
                - name: DB_DUMP_FREQ
                  value: "1440"
                - name: DB_HOST
                  value: freescout-db
                - name: DB_NAME
                  value: freescout
                - name: DB_PASS
                  value: freescout
                - name: DB_TYPE
                  value: mariadb
                - name: DB_USER
                  value: freescout
                - name: MD5
                  value: "TRUE"
              image: tiredofit/db-backup
              name: freescout-db-backup
              resources: {}
              volumeMounts:
                - mountPath: /backup
                  name: freescout-db-backup-claim0
          restartPolicy: Always
          volumes:
            - name: freescout-db-backup-claim0
              persistentVolumeClaim:
                claimName: freescout-db-backup-claim0
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: freescout-db-backup-claim0
      name: freescout-db-backup-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}

